const {
   getUsers,
   createUser,
   deleteUser,
   updateUser,
   getUser,
   Recovery,
} = require('../controllers/usuarios');
const {
   uploadDoc,
   getDocs,
   AddDocument,
   getDocsByCasoId,
   deleteDocsById,
} = require('../controllers/documentos');
const {
   getFotos,
   saveFotos,
   getFotoByCasoId,
   deleteFotos,
} = require('../controllers/fotos');
const {
   getCasos,
   getOne,
   createCaso,
   updateCaso,
   getCasosByDate,
   deleteCaso,
   importData,
   CambiarEstatus,
} = require('../controllers/casos');
const {
   addPersonal,
   getPersonal,
   getPersonalById,
   updatePersonal,
   deletePersonal,
   addDocs,
   getPersonalByDate,
   importPersonal,
} = require('../controllers/personal');

module.exports = {
   uploadDoc,
   getDocs,
   getUsers,
   createUser,
   deleteUser,
   updateUser,
   getUser,
   getCasos,
   getOne,
   createCaso,
   updateCaso,
   getFotoByCasoId,
   deleteCaso,
   getCasosByDate,
   CambiarEstatus,
   getFotos,
   AddDocument,
   getDocsByCasoId,
   importData,
   saveFotos,
   deleteFotos,
   addPersonal,
   getPersonal,
   getPersonalById,
   getPersonalByDate,
   updatePersonal,
   deletePersonal,
   addDocs,
   deleteDocsById,
   importPersonal,
};
